In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import pickle

In [2]:
df = pd.read_csv('absorbance.csv')
df

    s.no  time   5ml/min  10ml/min  15ml/min  20ml/min
0      1     0       NaN       NaN       NaN       NaN
1      2     5       NaN       NaN       NaN  4.410776
2      3    10       NaN       NaN  3.891820  3.891820
3      4    15       NaN  3.891820  3.127178  3.178054
4      5    20       NaN  3.178054  2.751535  2.751535
5      6    25       NaN  2.787562  2.402267  2.442347
6      7    30  3.748992  2.733942  2.313635  1.992430
7      8    35  3.152319  2.442347  1.992430  1.152680
8      9    40  2.699549  2.197225  1.516347  0.944462
9     10    45  2.586689  1.734601  1.208311  0.753772
10    11    50  2.442347  1.386294  0.895384  0.575364
11    12    55  2.289456  0.994623  0.619039  0.363965
12    13    60  1.900959  0.753772  0.438913  0.160343
13    14    65  1.098612  0.489548  0.200671 -0.120144
14    15    70  0.895384  0.363965  0.040005 -0.322773
15    16    75  0.753772  0.120144 -0.080043 -0.489548
16    17    80  0.532217 -0.200671 -0.322773 -0.753772
17    18    85  0.363965 -0.363965 -0.489548 -0.944462
18    19    90  0.160343 -0.489548 -0.800119 -1.152680
19    20    95 -0.080043 -0.753772 -1.098612 -1.585627
20    21   100 -0.281851 -0.895384 -1.324925 -1.992430
21    22   105 -0.532217 -1.152680 -1.386294 -2.751535
22    23   110 -0.753772 -1.386294 -1.734601 -3.178054
23    24   115 -0.895384 -1.734601 -2.313635 -3.476099
24    25   120 -1.152680 -2.313635 -2.586689 -3.891820
25    26   125 -1.516347 -2.442347 -2.751535       NaN
26    27   130 -2.313635 -3.178054 -3.891820       NaN
27    28   135 -2.751535 -3.178054       NaN       NaN
28    29   140 -2.944439 -3.178054       NaN       NaN

In [3]:
df.shape

(29, 6)

In [4]:
df.isnull().sum()

s.no        0
time        0
5ml/min     6
10ml/min    3
15ml/min    4
20ml/min    5
dtype: int64

In [5]:
df = df.select_dtypes(include =['int64','float64']) 
df

    s.no  time   5ml/min  10ml/min  15ml/min  20ml/min
0      1     0       NaN       NaN       NaN       NaN
1      2     5       NaN       NaN       NaN  4.410776
2      3    10       NaN       NaN  3.891820  3.891820
3      4    15       NaN  3.891820  3.127178  3.178054
4      5    20       NaN  3.178054  2.751535  2.751535
5      6    25       NaN  2.787562  2.402267  2.442347
6      7    30  3.748992  2.733942  2.313635  1.992430
7      8    35  3.152319  2.442347  1.992430  1.152680
8      9    40  2.699549  2.197225  1.516347  0.944462
9     10    45  2.586689  1.734601  1.208311  0.753772
10    11    50  2.442347  1.386294  0.895384  0.575364
11    12    55  2.289456  0.994623  0.619039  0.363965
12    13    60  1.900959  0.753772  0.438913  0.160343
13    14    65  1.098612  0.489548  0.200671 -0.120144
14    15    70  0.895384  0.363965  0.040005 -0.322773
15    16    75  0.753772  0.120144 -0.080043 -0.489548
16    17    80  0.532217 -0.200671 -0.322773 -0.753772
17    18    85  0.363965 -0.363965 -0.489548 -0.944462
18    19    90  0.160343 -0.489548 -0.800119 -1.152680
19    20    95 -0.080043 -0.753772 -1.098612 -1.585627
20    21   100 -0.281851 -0.895384 -1.324925 -1.992430
21    22   105 -0.532217 -1.152680 -1.386294 -2.751535
22    23   110 -0.753772 -1.386294 -1.734601 -3.178054
23    24   115 -0.895384 -1.734601 -2.313635 -3.476099
24    25   120 -1.152680 -2.313635 -2.586689 -3.891820
25    26   125 -1.516347 -2.442347 -2.751535       NaN
26    27   130 -2.313635 -3.178054 -3.891820       NaN
27    28   135 -2.751535 -3.178054       NaN       NaN
28    29   140 -2.944439 -3.178054       NaN       NaN

In [6]:
newdf = df.fillna({
    '5ml/min' :0,
    '10ml/min' :0,
    '15ml/min' :0,
    '20ml/min' :0,
})

In [7]:
newdf

    s.no  time   5ml/min  10ml/min  15ml/min  20ml/min
0      1     0  0.000000  0.000000  0.000000  0.000000
1      2     5  0.000000  0.000000  0.000000  4.410776
2      3    10  0.000000  0.000000  3.891820  3.891820
3      4    15  0.000000  3.891820  3.127178  3.178054
4      5    20  0.000000  3.178054  2.751535  2.751535
5      6    25  0.000000  2.787562  2.402267  2.442347
6      7    30  3.748992  2.733942  2.313635  1.992430
7      8    35  3.152319  2.442347  1.992430  1.152680
8      9    40  2.699549  2.197225  1.516347  0.944462
9     10    45  2.586689  1.734601  1.208311  0.753772
10    11    50  2.442347  1.386294  0.895384  0.575364
11    12    55  2.289456  0.994623  0.619039  0.363965
12    13    60  1.900959  0.753772  0.438913  0.160343
13    14    65  1.098612  0.489548  0.200671 -0.120144
14    15    70  0.895384  0.363965  0.040005 -0.322773
15    16    75  0.753772  0.120144 -0.080043 -0.489548
16    17    80  0.532217 -0.200671 -0.322773 -0.753772
17    18    85  0.363965 -0.363965 -0.489548 -0.944462
18    19    90  0.160343 -0.489548 -0.800119 -1.152680
19    20    95 -0.080043 -0.753772 -1.098612 -1.585627
20    21   100 -0.281851 -0.895384 -1.324925 -1.992430
21    22   105 -0.532217 -1.152680 -1.386294 -2.751535
22    23   110 -0.753772 -1.386294 -1.734601 -3.178054
23    24   115 -0.895384 -1.734601 -2.313635 -3.476099
24    25   120 -1.152680 -2.313635 -2.586689 -3.891820
25    26   125 -1.516347 -2.442347 -2.751535  0.000000
26    27   130 -2.313635 -3.178054 -3.891820  0.000000
27    28   135 -2.751535 -3.178054  0.000000  0.000000
28    29   140 -2.944439 -3.178054  0.000000  0.000000

In [8]:
x = newdf[['time']].values
y1 = newdf['5ml/min'].values

In [9]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y1_train,y1_test = train_test_split(x,y1,random_state=5)

In [10]:
from sklearn.tree import DecisionTreeRegressor
dt1=DecisionTreeRegressor(random_state=0,criterion="absolute_error")
dt1.fit(x_train,y1_train)
pre1 = dt1.predict(x_test)

In [11]:
from sklearn.metrics import r2_score
r2_score(y1_test,pre1)

0.942019084598186

In [12]:
print(dt1.predict([[30]]))

[3.74899244]

In [13]:
y2 = newdf['10ml/min'].values

In [14]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y2_train,y2_test = train_test_split(x,y2,random_state=5)

In [15]:
from sklearn.tree import DecisionTreeRegressor
dt2=DecisionTreeRegressor(random_state=0,criterion="absolute_error")
dt2.fit(x_train,y2_train)
pre2 = dt2.predict(x_test)

In [16]:
from sklearn.metrics import r2_score
r2_score(y2_test,pre2)

0.9503197657309078

In [17]:
print(dt2.predict([[30]]))

[2.73394161]

In [18]:
y3 = newdf['15ml/min'].values

In [19]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y3_train,y3_test = train_test_split(x,y3,random_state=5)

In [20]:
from sklearn.tree import DecisionTreeRegressor
dt3=DecisionTreeRegressor(random_state=0,criterion="absolute_error")
dt3.fit(x_train,y3_train)
pre3 = dt3.predict(x_test)

In [21]:
from sklearn.metrics import r2_score
r2_score(y3_test,pre3)

0.576839744692576

In [22]:
print(dt3.predict([[30]]))

[2.31363493]

In [23]:
y4 = newdf['20ml/min'].values

In [24]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y4_train,y4_test = train_test_split(x,y4,random_state=5)

In [25]:
from sklearn.tree import DecisionTreeRegressor
dt4=DecisionTreeRegressor(random_state=0,criterion="absolute_error")
dt4.fit(x_train,y4_train)
pre4 = dt4.predict(x_test)

In [26]:
from sklearn.metrics import r2_score
r2_score(y4_test,pre4)

0.9690995510267004

In [27]:
print(dt4.predict([[30]]))

[1.99243017]

In [28]:
pickle.dump(dt1,open('model1.pkl','wb'))
model=pickle.load(open('model1.pkl','rb'))

In [29]:
pickle.dump(dt2,open('model2.pkl','wb'))
model=pickle.load(open('model2.pkl','rb'))

In [30]:
pickle.dump(dt3,open('model3.pkl','wb'))
model=pickle.load(open('model3.pkl','rb'))

In [31]:
pickle.dump(dt4,open('model4.pkl','wb'))
model=pickle.load(open('model4.pkl','rb'))